<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda [
<!ELEMENT tienda (cd)*>
<!ELEMENT cd (titulo, artista, pais, compañia_discografica, precio, año_de_publicacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT compañia_discografica (#PCDATA)>
<!ELEMENT año_de_publicacion (#PCDATA)>]>
<tienda>

<cd>
<titulo>Still got the blues</titulo>
<artista>Gary Moore</artista>
<pais>UK</pais>
<compañia_discografica>Virgin Records</compañia_discografica>
<precio>10.20</precio>
<año_de_publicacion>1990</año_de_publicacion>
</cd>

<cd>
<titulo>One Night Only</titulo>
<artista>Bee Gees</artista>
<pais>UK</pais>
<compañia_discografica>Polydor</compañia_discografica>
<precio>10.90</precio>
<año_de_publicacion>1998</año_de_publicacion>
</cd>

<cd>
<titulo>When a man loves a woman</titulo>
<artista>Percy Sledge</artista>
<pais>USA</pais>
<compañia_discografica>Atlantic</compañia_discografica>
<precio>8.70</precio>
<año_de_publicacion>1987</año_de_publicacion>
</cd>

<cd>
<titulo>Big Willie style</titulo>
<artista>Will Smith</artista>
<pais>USA</pais>
<compañia_discografica>Columbia</compañia_discografica>
<precio>9.90</precio>
<año_de_publicacion>1987</año_de_publicacion>
</cd>

<cd>
<titulo>La canción de Juan perro</titulo>
<artista>Radio Futura</artista>
<pais>ESPAÑA</pais>
<compañia_discografica>Sony Music Aryola</compañia_discografica>
<precio>9.90</precio>
<año_de_publicacion>1987</año_de_publicacion>
</cd>

<cd>
<titulo>The dock of the day</titulo>
<artista>Otis Redding</artista>
<pais>USA</pais>
<compañia_discografica>Atlantic</compañia_discografica>
<precio>7.90</precio>
<año_de_publicacion>1987</año_de_publicacion>
</cd>

</tienda>